spring:
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${ip}:3306/summerlearning
    username: root
    password: qyml20030914
ip: localhost

server:
  port: 1145

  servlet:
    session:
      timeout: 30m
  tomcat:
    connection-timeout: 60000



